[package]
name = "test-macros"
version = "0.1.0"
authors = ["Julius de Bruijn <bruijn@prisma.io>"]
edition = "2021"
resolver = "2"

[lib]
proc-macro = true

[dependencies]
resolver-test = { path = "../" }
